version: '3.8'
services:
  node-api:
    build: ./node-api
    ports:
      - "3000:3000"
    volumes:
      - ./node-api/uploads:/usr/src/app/uploads # 사진 업로드 폴더와 컨테이너 링크

  kotlin-api:
    build: ./kotlin-api
    ports:
      - "8080:8080"

  nginx:
    image: nginx:latest
    ports:
      - "7001:7001"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - node-api
      - kotlin-api
